package vivadaylight3.genomics.common;

import hangcow.greatersecurity.common.GreaterSecurity;

import java.io.File;
import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

/**
 * Genomics main class
 * @author VivaDaylight3
 *
 */

@Mod(modid=Genomics.MOD_ID, name=Genomics.MOD_NAME, version=Genomics.MOD_VERSION, dependencies = Genomics.MOD_DEPENDENCIES)
@NetworkMod(clientSideRequired=true, serverSideRequired=false, channels =Genomics.MOD_CHANNEL, packetHandler = GenomicsPacketHandler.class)
public class Genomics
{
	
	public static final String MOD_ID = "Genomics";
	public static final String MOD_ID_LOWER = "genomics";
	public static final String MOD_NAME = "Molecular Genomics";
	public static final String MOD_VERSION = "0.0.1";
	public static final String MOD_DEPENDENCIES = "";
	
	@SidedProxy(clientSide = "vivadaylight3." + Genomics.MOD_ID_LOWER + ".client.ClientProxy", serverSide = "vivadaylight3." + Genomics.MOD_ID_LOWER + ".common.CommonProxy")
	public static final String MOD_CHANNEL = Genomics.MOD_ID;
	
	public static CommonProxy proxy;
	
	public static final int ID_BLOCK = 1551;
	public static final int ID_ITEM = 3853;
	
	@Metadata(Genomics.MOD_ID)
	public static ModMetadata meta;
	
	public static final String RESOURCE_PATH = "/mods/" + Genomics.MOD_ID_LOWER + "/";
	public static final String TEXTURE_PATH = RESOURCE_PATH + "textures/";
	public static final String BLOCK_PATH = TEXTURE_PATH + "blocks/";
	public static final String ITEM_PATH = TEXTURE_PATH + "items/";
	public static final String GUI_PATH = TEXTURE_PATH + "gui/";
	public static final String LANG_PATH = RESOURCE_PATH + "langauges/";
	public static final String TEXTURE_PREFIX = Genomics.MOD_ID_LOWER + ":";
	
	private static Configuration config = new Configuration(new File(Loader.instance().getConfigDir(), MOD_ID + ".cfg"));
	
	private static int blockSonicatorID;
	
	@Instance(MOD_NAME)
	public static Genomics instance;
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event){
	
		// Config
		config.load();
		blockSonicatorID = config.get(Configuration.CATEGORY_BLOCK, "Sonicator", ID_BLOCK).getInt();
		config.save();
		
		proxy.preInit();
		
	}
	
	public static CreativeTabs tabGenomics = new CreativeTabs("tab" + MOD_ID){
        
        public ItemStack getIconItemStack() {
        	
                return new ItemStack(Genomics.blockSonicator, 1, 0);
                
        }
	};
	
	// Blocks
	public static final Block blockSonicator = new BlockSonicator(blockSonicatorID);
	
	@Init
	public void mainInit(FMLInitializationEvent event){
		
		proxy.init();
		
		meta.modId = Genomics.MOD_ID;
		meta.name = Genomics.MOD_NAME;
		meta.description = "Extends the animla breeding and culling experience";
		meta.url = "https://github.com/VivaDaylight3/geonomics";

		meta.logoFile = GreaterSecurity.TEXTURE_PATH + "GP_Banner.png";
		meta.version = GreaterSecurity.VERSION;
		meta.authorList = Arrays.asList(new String[] { "DarkGuardsman", "TheCowGod" });
		meta.credits = "Please see the website.";
		meta.autogenerated = false;
		
		GameRegistry.registerBlock(blockSonicator, "Sonicator");
		
		LanguageRegistry.instance().addStringLocalization("itemGroup.tab" + MOD_ID, "en_GB", MOD_NAME);
		
	}
	
}
